<<<<<<< HEAD
# Site
name: 'Girgit Communication'
description: 'building up next generation UCaaS System '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/girgit-communication'
disqus: 'demowebsite'
email: 'pankaj.index@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           pankaj
      site:           https://business-expert.github.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am pankaj and working as project manager "
      email:          pankaj.index@gmail.com
             

  
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
=======
theme: jekyll-theme-minimal
title: Girgit Communication 
description: your all voip UCaaS and CPaaS systemm development help 

